const MEDIA_PATH = "/api/feishu-media";

export function losslessArticleImageSource(src: string | undefined): string | undefined {
  // Only rewrite the signed, same-origin URLs generated by our Feishu importer.
  // External images, attachment links and stored article data stay untouched.
  if (!src?.startsWith(`${MEDIA_PATH}?`)) return undefined;
  const url = new URL(src, "https://article-image.invalid");
  if (!["image", "board"].includes(url.searchParams.get("type") ?? "") ||
      !url.searchParams.get("token") || !url.searchParams.get("sig")) return undefined;
  url.searchParams.set("format", "webp-lossless-v1");
  return `${url.pathname}${url.search}${url.hash}`;
}
